[aggregator]
ttl = 600

[anilist_api]
url = "https://graphql.anilist.co"

[db]

[db.mongodb]
uri = "mongodb://host.docker.internal:27017"
database = "test"

[db.redis]
uri = "redis://host.docker.internal:6379"

[subsplease]

[subsplease.rss]
url = "https://subsplease.org/rss/?t&r=720"

[subsplease.scraper]
url = "https://subsplease.org/schedule/"
webdriver_url = "http://localhost:9515"
chrome_options = "--headless --disable-gpu --no-sandbox --disable-dev-shm-usage"

[transform]
similarity_threshold = 0.35

[worker]
retry_timeout = 10
